import type { Product } from '../types'

export const ALL_CATEGORY_ID = 'all'
export const PRODUCT_PAGE_SIZE = 6

export const PRODUCT_CATEGORIES = [
  { id: 'all', name: 'Tất cả' },
  { id: 'ruou-nep-trang', name: 'Rượu nếp trắng' },
  { id: 'cuu-long-my-tuu', name: 'Cửu Long Mỹ Tửu' },
  { id: 'ruou-500-anh-em', name: 'Rượu 500 Anh Em' },
  { id: 'ruou-lang', name: 'Rượu Làng' },
  { id: 'ruou-mam', name: 'Rượu Mầm' },
]

export const MOCK_PRODUCTS: Product[] = [
  // 1. Rượu nếp trắng (1 sản phẩm)
  {
    id: 'ruou-nep-trang-cuu-long',
    name: 'Rượu nếp trắng Cửu Long',
    category: 'ruou-nep-trang',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🔥 Bán chạy',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Chưng cất thủ công chuẩn vị nếp trắng miền Tây, êm dịu nồng đằm say đắm.',
    capacity: '500ml',
    alcoholByVolume: '29% vol',
    filterStyle: 'grayscale(1) brightness(1.25) contrast(1.1)', // Chai trong suốt/màu xám bạc
    tags: ['Cao cấp'],
    price: 176000,
    priceText: '176.000đ',
  },
  // 2. Cửu Long Mỹ Tửu (3 sản phẩm)
  {
    id: 'hoang-hoa-tuu',
    name: 'Hoàng Hoa Tửu - Bình sứ Bát Tràng',
    category: 'cuu-long-my-tuu',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🔥 Bán chạy',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Rượu gạo cúc vàng hạ thổ hảo hạng, sắc vàng hổ phách tinh khiết quý phái.',
    capacity: '500ml',
    alcoholByVolume: '32% vol',
    filterStyle: 'hue-rotate(145deg) saturate(1.4) brightness(0.95)', // Chai màu hổ phách
    tags: ['Biếu', 'Cao cấp', 'Combo'],
    price: 770000,
    priceText: '770.000đ',
  },
  {
    id: 'minh-mang-tuu',
    name: 'Minh Mạng Tửu - Bình sứ Bát Tràng',
    category: 'cuu-long-my-tuu',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '👑 Thượng hạng',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Phục dựng theo công thức ngự tửu cung đình triều Nguyễn, đại bổ khí huyết.',
    capacity: '500ml',
    alcoholByVolume: '35% vol',
    filterStyle: '', // Màu xanh cobalt gốc sang trọng
    tags: ['Biếu', 'Combo'],
    price: 770000,
    priceText: '770.000đ',
  },
  {
    id: 'dong-trung-ha-thao-tuu',
    name: 'Đông Trùng Hạ Thảo Tửu - Bình sứ',
    category: 'cuu-long-my-tuu',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🌟 Quý hiếm',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Ngâm ủ từ đông trùng hạ thảo tươi nguyên sinh Tây Tạng, tốt cho sức khoẻ.',
    capacity: '500ml',
    alcoholByVolume: '32% vol',
    filterStyle: 'hue-rotate(60deg) saturate(1.2) brightness(0.85)', // Chai rêu vàng ấm
    tags: ['Biếu', 'Cao cấp'],
    price: 880000,
    priceText: '880.000đ',
  },
  // 3. Rượu 500 Anh Em (1 sản phẩm)
  {
    id: 'ruou-500-anh-em',
    name: 'Rượu Gạo 500 Anh Em - Kết Giao Tri Kỷ',
    category: 'ruou-500-anh-em',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🤝 Hữu nghị',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Vị nồng ấm, êm sảng khoái, chất rượu gắn kết tình nghĩa bằng hữu keo sơn.',
    capacity: '1000ml',
    alcoholByVolume: '29% vol',
    filterStyle: 'hue-rotate(220deg) saturate(1.3) brightness(0.8)', // Chai tím thạch anh
    tags: ['Combo'],
    price: 350000,
    priceText: '350.000đ',
  },
  // 4. Rượu Làng (4 sản phẩm)
  {
    id: 'ruou-lang-van',
    name: 'Rượu Nếp Làng Vân Danh Tiếng',
    category: 'ruou-lang',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🌾 Cổ xưa',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Đặc sản Kinh Bắc danh bất hư truyền, vị ngọt êm dịu, thơm nồng lúa nếp.',
    capacity: '500ml',
    alcoholByVolume: '40% vol',
    filterStyle: 'hue-rotate(100deg) saturate(1.1) brightness(0.9)', // Chai xanh lá tre
    tags: ['Cao cấp'],
    price: 195000,
    priceText: '195.000đ',
  },
  {
    id: 'ruou-go-cong',
    name: 'Rượu Đế Gò Đen Long An',
    category: 'ruou-lang',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🍂 Truyền thống',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Nấu từ nếp than tuyển chọn bằng men thảo mộc truyền thống Nam Bộ.',
    capacity: '500ml',
    alcoholByVolume: '38% vol',
    filterStyle: 'hue-rotate(330deg) saturate(1.1) brightness(0.9)', // Chai đỏ đô
    tags: ['Cao cấp', 'Combo'],
    price: 180000,
    priceText: '180.000đ',
  },
  {
    id: 'ruou-bau-da',
    name: 'Rượu Bàu Đá Bình Định Bình Sứ',
    category: 'ruou-lang',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🔥 Mạnh mẽ',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Chưng cất từ nguồn nước ngầm Bàu Đá thiêng liêng, hương nồng đậm đà đặc trưng.',
    capacity: '500ml',
    alcoholByVolume: '50% vol',
    filterStyle: 'hue-rotate(180deg) saturate(1.2) brightness(0.95)', // Chai xanh ngọc bích
    tags: ['Biếu'],
    price: 220000,
    priceText: '220.000đ',
  },
  {
    id: 'ruou-san-lung',
    name: 'Rượu Sán Lùng Lào Cai Độc Đáo',
    category: 'ruou-lang',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🏔️ Tây Bắc',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Ủ từ hạt thóc nương đỏ chín mọng cùng men lá rừng thơm ngát sương sớm.',
    capacity: '500ml',
    alcoholByVolume: '35% vol',
    filterStyle: 'hue-rotate(45deg) saturate(1.4) brightness(0.85)', // Chai vàng nâu gốm nung
    tags: ['Cao cấp'],
    price: 200000,
    priceText: '200.000đ',
  },
  // 5. Rượu Mầm (4 sản phẩm)
  {
    id: 'ruou-mam-thoc',
    name: 'Rượu Mầm Thóc Tây Bắc Tươi Mát',
    category: 'ruou-mam',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🌱 Tự nhiên',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Chiết xuất lên men tự nhiên từ mầm thóc nương chín sữa non, thanh ngọt dễ uống.',
    capacity: '500ml',
    alcoholByVolume: '18% vol',
    filterStyle: 'hue-rotate(85deg) saturate(1.2) brightness(0.9)', // Chai xanh lục nhạt
    tags: ['Cao cấp', 'Combo'],
    price: 165000,
    priceText: '165.000đ',
  },
  {
    id: 'ruou-mam-lua-mach',
    name: 'Rượu Mầm Lúa Mạch Thượng Hạng',
    category: 'ruou-mam',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '✨ Ưa thích',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Men lúa mạch nhập khẩu kết hợp quy trình chưng cất hạ thổ đặc sản Việt.',
    capacity: '500ml',
    alcoholByVolume: '25% vol',
    filterStyle: 'hue-rotate(120deg) saturate(1.5) brightness(0.8)', // Chai lục bảo đậm
    tags: ['Biếu', 'Cao cấp'],
    price: 290000,
    priceText: '290.000đ',
  },
  {
    id: 'ruou-mam-gao-luc',
    name: 'Rượu Mầm Gạo Lức Huyết Rồng',
    category: 'ruou-mam',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '❤️ Bổ dưỡng',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Hạt gạo lức huyết rồng lên mầm tự nhiên, ủ tĩnh 3 năm hạ thổ sâu sắc.',
    capacity: '500ml',
    alcoholByVolume: '24% vol',
    filterStyle: 'hue-rotate(300deg) saturate(1.4) brightness(0.85)', // Chai tím hồng ngoại
    tags: ['Cao cấp'],
    price: 230000,
    priceText: '230.000đ',
  },
  {
    id: 'ruou-mam-sen',
    name: 'Rượu Mầm Hạt Sen Đồng Tháp',
    category: 'ruou-mam',
    image: '/products/hoang_hoa_tuu.png',
    badgeText: '🌸 Thanh tao',
    brandText: 'somo gold',
    hotline: '0902 931 119',
    description: 'Kết tinh từ hạt sen Đồng Tháp Mười nẩy mầm, hương thơm dịu nhẹ ngủ ngon giấc.',
    capacity: '500ml',
    alcoholByVolume: '19% vol',
    filterStyle: 'hue-rotate(250deg) saturate(1.2) brightness(0.9)', // Chai xanh oải hương
    tags: ['Biếu', 'Combo'],
    price: 250000,
    priceText: '250.000đ',
  },
]
